<style type="text/css">
    .actions-divider {
        padding      : 10px;
        background   : #fafafa;
        color        : #444;
        -moz-tab-size: 4;
        tab-size     : 4;
        border       : 1px solid #ddd;
        border-radius: 5px;
        -webkit-border-radius: 5px;
        -moz-border-radius: 5px;
    }

    .action-icons {
        margin-top:15px;
        margin-bottom:55px;
        font-size: 40px;
    }

    .actions-divider h1 {
        line-height  : 10px;
        width: 100%;
        font-size:25px;
    }

    .icon-stack {
        margin-left:20px;
    }

    .icon-stack i span {
        color: #555;
        position: relative;
        font: normal 14px/18px 'Quattrocento Sans', sans-serif;
        text-align: center;
        display: block;
    }

    .cpanel-host-info {
        font-size:12px;
        margin-right: 20px;
    }

</style>

<table width="100%">
    <tr>
        <td width="300" valign="top">
<div class="alert ce-alert ce-alert-info cpanel-host-info">
    Main Domain formydad.com <br/>
    Server: skeleton.domain.com <br/>
    Disk Space Used: .22/ unlimited <br/>
    Monthly Bandwidth 0/unlimited

<br/><br/>
more data?

</div>

</td>
<td>

    <div class="actions-divider">
        <h1><?php echo $this->user->lang("Email");?></h1>
    </div>

    <div class="action-icons">
        <span class="icon-stack">
          <i class="icon-circle icon-stack-base"></i>
          <i class="wh-icon-emailalt icon-light"><span><?php echo $this->user->lang("Email Accounts");?></span></i>
        </span>

        <span class="icon-stack">
          <i class="icon-circle icon-stack-base"></i>
          <i class="wh-icon-emailforwarders icon-light"><span><?php echo $this->user->lang("Forwarders");?></span></i>
        </span>
    </div>

    <div class="actions-divider">
        <h1><?php echo $this->user->lang("FTP");?></h1>
    </div>

    <div class="action-icons">
        <span class="icon-stack">
          <i class="icon-circle icon-stack-base"></i>
          <i class="wh-icon-ftpaccounts icon-light"><span><?php echo $this->user->lang("FTP Accounts");?></span></i>
        </span>
    </div>

    <div class="actions-divider">
        <h1><?php echo $this->user->lang("Databases");?></h1>
    </div>

    <div class="action-icons">
        <span class="icon-stack">
          <i class="icon-circle icon-stack-base"></i>
          <i class="wh-icon-database icon-light"><span><?php echo $this->user->lang("MySQL Databases");?></span></i>
        </span>


        <span class="icon-stack">
          <i class="icon-circle icon-stack-base"></i>
          <i class="wh-icon-groups-friends icon-light"><span><?php echo $this->user->lang("Database Users");?></span></i>
        </span>

        <span class="icon-stack">
          <i class="icon-circle icon-stack-base"></i>
          <i class="icon-table icon-light"><span><?php echo $this->user->lang("phpMyAdmin");?></span></i>
        </span>

    </div>

    <div class="actions-divider">
        <h1><?php echo $this->user->lang("Domains");?></h1>
    </div>

    <div class="action-icons">
        <span class="icon-stack">
          <i class="icon-circle icon-stack-base"></i>
          <i class="wh-icon-parkeddomain icon-light"><span><?php echo $this->user->lang("Parked Domains");?></span></i>
        </span>

        <span class="icon-stack">
          <i class="icon-circle icon-stack-base"></i>
          <i class="wh-icon-subdomain icon-light"><span><?php echo $this->user->lang("Subdomains");?></span></i>
        </span>

        <span class="icon-stack">
          <i class="icon-circle icon-stack-base"></i>
          <i class="wh-icon-domainaddon icon-light"><span><?php echo $this->user->lang("Addon Domains");?></span></i>
        </span>

    </div>
</td>
</tr>
</table>